# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: "/storage_common/nobilm/ml-simplefold/"

tmp_dir: ${paths.output_dir}/tmp/

# path to data directory
data_dir: ${paths.root_dir}data/

# path to logging directory
log_dir: ${paths.root_dir}logs/

# artifacts directory
output_dir: ${paths.root_dir}artifacts/

sample_dir: ${.output_dir}/samples/

# path to working directory
work_dir: ${hydra:runtime.cwd}
